### ISSUE TITLE
titile 

### ISSUE THREAD

**Issue by Darian1996** [houbb/markdown-toc#5]
![image](https://user-images.githubusercontent.com/37619525/61239137-c7b1ba00-a770-11e9-9087-ed09d55b5551.png)

就是字节码编译出来的，我放到 ```java ```
中间的，会出现了多出来了。这怎么处理

**Comment by houbb** [comment]
字节码编译是放在代码块中的，并且以符号 `#` 开头对吗？

原因：以前没有考虑到这种场景，应该排除掉代码块中的信息。

解决方式：只能暂时手动删除。我本周有时间解决下这个 BUG，发布新的版本。到时和你说下。

如果方便的话，能将这个 markdown 文件的原始文件(内容/url) 发一下吗，我改好后方便验证下。

**Comment by houbb** [comment]
v1.0.7 修复代码块中的 `#` 也被当做标题的 BUG。

参考文件：[代码块文件](https://github.com/houbb/markdown-toc/blob/master/src/test/resources/CODE_BLOCK.md)

如果依然没有解决你的问题，麻烦提供下对应的 md 文件内容(URL)。

**Comment by Darian1996** [comment]
jar 包什么时候可以发布到中央仓库？

**Comment by gitbook-echo** [comment]
昨天已经发布了，今天应该可以下载到了。------------------ Original ------------------From: Darian  <notifications@github.com>Date: Wed,Jul 17,2019 0:18 AMTo: houbb/markdown-toc <markdown-toc@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [houbb/markdown-toc] titile  (#5)jar 包什么时候可以发布到中央仓库？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/houbb/markdown-toc/issues/5?email_source=notifications\u0026email_token=AKEEDA24HWLVENAL6H3WCITP7XYGTA5CNFSM4IDZQMCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2BMGWQ#issuecomment-511886170",
"url": "https://github.com/houbb/markdown-toc/issues/5?email_source=notifications\u0026email_token=AKEEDA24HWLVENAL6H3WCITP7XYGTA5CNFSM4IDZQMCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2BMGWQ#issuecomment-511886170",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by houbb** [comment]
> jar 包什么时候可以发布到中央仓库？

已经发布过了。

**Comment by Darian1996** [comment]
谢谢，看到了
