### ISSUE TITLE
目录

### ISSUE THREAD

**Issue by Darian1996** [houbb/markdown-toc#8]
有办法生成一个当前所有的工程所有文件的目录吗？

**Comment by gitbook-echo** [comment]
指定一个文件夹即可，可以生成该文件夹下所有文件的目录。指定 subTree=true，可以递归文件夹。发自我的iPhone------------------ 原始邮件 ------------------发件人: Darian  <notifications@github.com>发送时间: 2019年8月12日 22:53收件人: houbb/markdown-toc <markdown-toc@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[houbb/markdown-toc] 目录 (#8)有办法生成一个当前所有的工程所有文件的目录吗？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/houbb/markdown-toc/issues/8?email_source=notifications\u0026email_token=AKEEDA4HRVKVQ25V3UJD2BTQEF2OHA5CNFSM4ILCBLOKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HEXQGNQ",
"url": "https://github.com/houbb/markdown-toc/issues/8?email_source=notifications\u0026email_token=AKEEDA4HRVKVQ25V3UJD2BTQEF2OHA5CNFSM4ILCBLOKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HEXQGNQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by houbb** [comment]
指定一个文件夹即可，可以生成该文件夹下所有文件的目录。
指定 subTree=true，可以递归文件夹。
可参考{指定文件夹生成案例}(https://github.com/houbb/markdown-toc/blob/release_1.0.2/src/test/java/com/github/houbb/markdown/toc/core/impl/AtxMarkdownTocDirTest.java)

**Comment by Darian1996** [comment]
![image](https://user-images.githubusercontent.com/37619525/62908920-f7be9e00-bdac-11e9-903c-d841a384d7a8.png)

我的意思是这样子的目录
